model_nm: 'ocnn_lenet' 
n_epochs: 200
batch_size: 8
lr: 0.0001
weight_decay: 0.01
dropout: 0.1
early_stopping: True
model_ckpt_fpath: "ocnn_pretrained.ckpt"
octree_depth: 6
ocnn_stages: 4
ocnn_full_depth: 2
ocnn_features: "L" #See docs for more details: https://ocnn-pytorch.readthedocs.io/en/latest/modules/octree.html#ocnn.octree.Octree.get_input_feature
octree_nempty: False